# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient_descent_lsq <- function(y, A, x0, lambda, gamma, tol = 1e-4, max_iter = 10000L, printing = FALSE) {
    .Call(`_code815_gradient_descent_lsq`, y, A, x0, lambda, gamma, tol, max_iter, printing)
}

loss_ridge <- function(y, A, x, lambda) {
    .Call(`_code815_loss_ridge`, y, A, x, lambda)
}

stochastic_gradient_descent_lsq <- function(y, A, x0, lambda, batch, initial_step_size = 1.0, tol = 1e-6, max_iter = 10000L, printing = FALSE) {
    .Call(`_code815_stochastic_gradient_descent_lsq`, y, A, x0, lambda, batch, initial_step_size, tol, max_iter, printing)
}

